### PR TITLE
Switch from Travis CI to GitHub Actions CI

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@KristofferC What Julia versions do you want to run the benchmarks on?

Right now, I'm running the `Pkg.test()` on 1.0, 1.6, v1, and nightly. But I'm only running the benchmarks on nightly. Do you want to run the benchmarks on more versions of Julia, or just nightly?

**Comment by DilumAluthge** [comment]
Bump @KristofferC

**Comment by DilumAluthge** [comment]
Bump @KristofferC 

It would be good to get CI running on this repo again.

**Comment by KristofferC** [comment]
Thanks!

**Pull request merged**
